import{A as l,S as d,N as u,K as p,M as m}from"./assets/vendor-e47d4a2a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const g=document.querySelector(".header-burger"),n=document.querySelector(".modal"),f=document.querySelector(".menu-link");g.addEventListener("click",e=>{n.classList.add("active")});f.addEventListener("click",e=>{n.classList.toggle("active")});n.addEventListener("click",e=>{e.target!==e.currentTarget&&n.classList.remove("active")});new l(".accordion-container-first",{openOnInit:[0]});const h=["HTML/CSS","JavaScript","React","Node.js","React Native","Soft skills","TypeScript"],b=document.querySelector(".about-swiper-list");function v(){const e=document.querySelector(".next-btn"),r=new d(".about-swiper",{speed:400,slidesPerView:"auto",loop:!0,loopAddBlankSlides:!0,navigation:{nextEl:".swiper-button-next"},modules:[u]});e.addEventListener("click",()=>{r.slideNext()})}function j(e,r){const i=e.map(o=>`<li class="swiper-slide about-swiper-list-item"><p class="about-swiper-list-item-par">${o}</p></li>`).join("");r.insertAdjacentHTML("beforeend",i)}j(h,b);v();const w=document.querySelector(".project-swiper-wrapper"),L=[{title:"Project 1",skills:["#react","#js","#node js","#git"],description:"Programming Across Borders: Ideas, Technologies, Innovations",githubLink:"https://github.com",image:"../img/projects/Petlove-tell1@1x.jpg"},{title:"Project 2",skills:["#react","#js","#node js","#git"],description:"Programming Across Borders: Ideas, Technologies, Innovations",githubLink:"https://github.com",image:"../img/projects/ReadJourney-tell 1@1x.jpg"},{title:"Project 3",skills:["#react","#js","#node js","#git"],description:"Programming Across Borders: Ideas, Technologies, Innovations",githubLink:"https://github.com",image:"../img/projects/Register-tell1@1x.jpg"}];function y(e){return`
    <div class="swiper-slide project-swiper-slide">
    <div class="projects-container-content">
    <ul class="cards-container-projects">
     ${e.skills.map(i=>`<li class="project-card">${i}</li>`).join("")}
    </ul>
    <p class="title-project">${e.description}</p>
      <a href="${e.githubLink}" target="_blank" class="see-project">See project</a>
     
      <div class="container-projects-imgs">
      <img src="${e.image}" alt="${e.title}" class="projects-img">
     </div>
      </div>
    </div>
  `}const S=L.map(y).join("");w.innerHTML=S;new d(".swiper-container",{loop:!0,direction:"horizontal",speed:500,spaceBetween:20,centeredSlides:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0},mousewheel:{enabled:!0,forceToAxis:!0},modules:[u,p,m]});new l(".faq-list-one",{duration:400,showMultiple:!0});new l(".faq-list-two",{duration:400,showMultiple:!0});let a=document.querySelectorAll(".project-item-img"),k=new IntersectionObserver(e=>{e.forEach(r=>{r.isIntersecting?a.forEach(i=>i.classList.add("animation")):a.forEach(i=>i.classList.remove("animation"))})},{threshold:.05});const P=document.querySelector(".covers");k.observe(P);
//# sourceMappingURL=commonHelpers.js.map
