import{A as m,S as f,N as g,K as L,M as h,i as j,a as S}from"./assets/vendor-6c23e1b5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const E=document.querySelector(".header-burger"),u=document.querySelector(".modal"),k=document.querySelector(".menu-link");E.addEventListener("click",e=>{u.classList.add("active")});k.addEventListener("click",e=>{u.classList.toggle("active")});u.addEventListener("click",e=>{e.target!==e.currentTarget&&u.classList.remove("active")});new m(".accordion-container-first",{openOnInit:[0]});const x=["HTML/CSS","JavaScript","React","Node.js","React Native","Soft skills","TypeScript"],q=document.querySelector(".about-swiper-list");function A(){const e=document.querySelector(".next-btn"),s=new f(".about-swiper",{speed:400,slidesPerView:"auto",loop:!0,loopAddBlankSlides:!0,navigation:{nextEl:".swiper-button-next"},modules:[g]});e.addEventListener("click",()=>{s.slideNext()})}function _(e,s){const o=e.map(c=>`<li class="swiper-slide about-swiper-list-item"><p class="about-swiper-list-item-par">${c}</p></li>`).join("");s.insertAdjacentHTML("beforeend",o)}_(x,q);A();const P=document.querySelector(".project-swiper-wrapper"),M=[{title:"Project 1",skills:["#react","#js","#node&nbsp;js","#git"],description:"Programming Across<br>Borders: Ideas,<br> Technologies, Innovations",githubLink:"https://github.com",image:"../img/projects/Petlove-tell1@1x.jpg"},{title:"Project 2",skills:["#react","#js","#node js","#git"],description:"Programming Across Borders: Ideas, Technologies, Innovations",githubLink:"https://github.com",image:"../img/projects/ReadJourney-tell 1@1x.jpg"},{title:"Project 3",skills:["#react","#js","#node js","#git"],description:"Programming Across Borders: Ideas, Technologies, Innovations",githubLink:"https://github.com",image:"../img/projects/Register-tell1@1x.jpg"}];function T(e){return`
    <div class="swiper-slide project-swiper-slide">
    <div class="projects-container-content">
    <ul class="cards-container-projects">
     ${e.skills.map(o=>`<li class="project-card">${o}</li>`).join("")}
    </ul>
    <p class="title-project">${e.description}</p>
      <a href="${e.githubLink}" target="_blank" class="see-project">See project</a>
     
      <div class="container-projects-imgs">
      <img src="${e.image}" alt="${e.title}" class="projects-img">
     </div>
      </div>
    </div>
  `}const $=M.map(T).join("");P.innerHTML=$;new f(".swiper-container",{loop:!0,direction:"horizontal",speed:500,spaceBetween:20,centeredSlides:!0,navigation:{nextEl:".swiper-button-next-project",prevEl:".swiper-button-prev-project"},keyboard:{enabled:!0},mousewheel:{enabled:!0,forceToAxis:!0},modules:[g,L,h]});new m(".faq-list-one",{duration:400,showMultiple:!0});new m(".faq-list-two",{duration:400,showMultiple:!0});let v=document.querySelectorAll(".project-item-img"),I=new IntersectionObserver(e=>{e.forEach(s=>{s.isIntersecting?v.forEach(o=>o.classList.add("animation")):v.forEach(o=>o.classList.remove("animation"))})},{threshold:.05});const N=document.querySelector(".covers");I.observe(N);const R="https://portfolio-js.b.goit.study/api",B="/reviews",b=document.querySelector(".js-reviews-list");async function O(){const e=`${R}${B}`,{data:s}=await S.get(e);return s}function C(e){return e.map(s=>{const{author:o,avatar_url:c,review:r}=s;return`
<li class="gallery-item swiper-slide">
   <img class="gallery-image"
   src = "${c}"
   alt = "${o}"/>
   <h4 class="review-author ">${o}</h4>
   <p class="review-text">${r}</p>
</li>
`}).join("")}async function H(){try{const e=await O();b.insertAdjacentHTML("beforeend",C(e)),V()}catch(e){z(e),b.insertAdjacentHTML("beforeend",`<li class="not-found-item">
    <p class="not-found-text">Not found</p></li>`)}}H();function V(){new f(".swiper-reviews",{modules:[g,L,h],direction:"horizontal",speed:500,slidesPerView:1,spaceBetween:16,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}},navigation:{nextEl:".swiper-btn-next",prevEl:".swiper-btn-prev"},keyboard:{enabled:!0},mousewheel:{enabled:!0,forceToAxis:!0}})}const w={messageSize:"16",messageLineHeight:"24",backgroundColor:"rgb(239, 64, 64)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",maxWidth:"432px"};function z(e){w.message=`Sorry, ${e} reviews not found!`,j.error(w)}document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("work-form");e.addEventListener("submit",s);async function s(t){t.preventDefault(),o()===0?d(e.querySelector("._req"),"Success!"):alert("Заполните обязательные поля")}function o(t){let i=0,a=document.querySelectorAll("._req");for(let p=0;p<a.length;p++){const l=a[p];r(l),l.classList.contains("_email")?n(l)&&(c(l,"Invalid email, try again"),i++):l.value===""&&(c(l,"This field is required"),i++)}return i}function c(t,i){t.parentElement.classList.add("_error"),t.classList.add("_error");const a=document.createElement("label");a.textContent=i,a.classList.add("_error"),t.parentElement.append(a)}function r(t){t.parentElement.classList.remove("_error"),t.classList.remove("_error");const i=t.parentElement.querySelector("label._error");i&&i.remove()}function n(t){return!/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,8})+$/.test(t.value)}function d(t,i){y(t),t.parentElement.classList.add("_approved"),t.classList.add("_approved");const a=document.createElement("label");a.textContent=i,a.classList.add("_approved"),t.parentElement.append(a)}function y(t){t.parentElement.classList.remove("_approved"),t.classList.remove("_approved");const i=t.parentElement.querySelector("label._approved");i&&i.remove()}});
//# sourceMappingURL=commonHelpers.js.map
